version: '3'

services:
  pulsar-heartbeat:
    image: 'datastax/pulsar-heartbeat:0.0.1'
    ports:
      - '8080:8080'
    volumes:
      - './config/kesque-pulsar.cert:/etc/ssl/certs/ca-bundle.crt'
      - './config/runtime.yml:/config/runtime.yml'
