FROM golang:1.16.7-stretch
ARG user=pulsar
ARG group=pulsar
ARG uid=1000
ARG gid=116

RUN groupadd --gid ${gid} ${group}
RUN useradd --uid ${uid} -g ${group} -m ${user}

COPY src/pulsar-heartbeat /home/${user}
RUN go get github.com/google/gops
RUN cp /go/bin/gops /home/${user}/gops

RUN chown -R ${user}:${group} /home/${user}
WORKDIR /home/${user}
USER ${user}
ENV PULSAR_OPS_MONITOR_CFG=/config/runtime.yml

ENTRYPOINT ./pulsar-heartbeat
