replicaCount: 1

image:
  repository: datastax/pulsar-heartbeat
  tag: latest
  pullPolicy: IfNotPresent

pulsarmonitor:
  component: "standalone-pulsar-heartbeat"
incluster: false

config:
  name: monitor-useast1-gcp-latency
  k8sInClusterMonitorEnabled: "false"
  alertUrl: https://hooks.slack.com/services/[slack app webhook]
  pulsarClientToken: eyJhbGciOiJSUzI1...[pulsar JWT]


#
# pubsub latency check
#
topicConfigs:
  - latencyBudgetMs: 999
    name: pubsub-latency-useast1-gcp-outcluster
    intervalSeconds: 120
    pulsarUrl: pulsar+ssl://useast1.gcp.kafkaesque.io:6651
    topicName: persistent://ming-luo/local-useast1-gcp/latency-test
    payloadSizes: [15B]
    numberOfMessages: 2
    alertPolicy:
      Ceiling: 5
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 5